# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2016

# Custom your favicon.ico in `site/source`
favicon: /favicon.png

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Categories: /categories/
  Tags: /tags/
  About: /about/
  # Tags: /tags
  # Categories: /categories
  # About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  search: false
  fancybox: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: true
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: baoyx007@gmail.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: https://github.com/Baoyx007
  weibo: http://weibo.com/u/2802352712
  # zhihu: 
  rss: /atom.xml

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics: UA-82395311-1

comments:
  post: true
  about: true

sidebar: true

# Duoshuo
# duoshuo_shortname:
# Disqus
disqus_shortname: byx
# netease
# netease_key:


# ===========================================
# Version
# ===========================================
version: 2.4.x

